# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties (gepinnt für Minecraft 1.21.11)
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.5
loom_version=1.17.21

# Mod Properties
version=1.0.0
group=com.gorgiibot

# Dependencies
fabric_api_version=0.141.6+1.21.11
